# Generated by Django 5.2.3 on 2026-05-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('class_test', 'Class Test'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual')], max_length=20)),
                ('class_level', models.IntegerField()),
                ('date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('compulsory', 'Compulsory'), ('optional_4th', 'Optional 4th')], max_length=20)),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business'), ('All', 'All')], default='All', max_length=20)),
                ('class_levels', models.JSONField()),
                ('has_practical', models.BooleanField(default=False)),
                ('full_marks', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('academic_year', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
    ]
